[package]
name = "byrdocs-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.211", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"
structopt = "0.3.26"
